# Generated by Django 4.2.3 on 2023-08-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=20, unique=True)),
                ('posterlink', models.CharField(max_length=50)),
                ('seriestitle', models.CharField(max_length=50)),
                ('releasedyear', models.CharField(max_length=5)),
                ('certification', models.CharField(max_length=5)),
                ('runtime', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=30)),
                ('IMDBrating', models.CharField(max_length=4)),
                ('overview', models.CharField(max_length=100)),
                ('metascore', models.CharField(max_length=5)),
                ('Director', models.CharField(max_length=20)),
                ('star1', models.CharField(max_length=20)),
                ('star2', models.CharField(max_length=20)),
                ('star3', models.CharField(max_length=20)),
                ('star4', models.CharField(max_length=20)),
                ('noofvotes', models.CharField(max_length=10)),
                ('gross', models.CharField(max_length=20)),
            ],
        ),
    ]
